name: Android CI

on:
    push:
        branches:
            - master
    pull_request:
        branches:
            - master
    workflow_dispatch: #Allow triggering builds manually from Actions tab in GitHub

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
      with:
        lfs: true

    - name: Set up JDK 17
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
        
    - name: Setup Android SDK
      uses: android-actions/setup-android@v2
    - run: sdkmanager "ndk;22.0.7026061"


    # NDK installation https://github.com/actions/runner-images/issues/60
  #  - name: Setup Android NDKv2
  #    run: ${ANDROID_HOME}/tools/bin/sdkmanager --install "ndk;22.0.7026061"

    - name: Grant execute permission for gradlew
      run: chmod +x gradlew
    - name: Get mock keys
      run: wget -O ./app/src/main/res/values/keys.xml https://devel.maajaam.ee/droon/rosettadrone/index.php?c=k
    - run: cat ./app/src/main/res/values/keys.xml
    - name: Build with Gradle
      run: ./gradlew build
    - name: Assabmle APK
      run: ./gradlew assemble
    - name: Upload APK Release
      uses: actions/upload-artifact@v3
      with:
        name: APK(s) release generated
        path: app/build/outputs/apk/release/
